my_site/my_blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'my_blog'
urlpatterns = [
    path('list/', views.ListView.as_view(), name='list'),
    path('<int:pk>/detail/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.EditView.as_view(), name='edit'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    re_path(r'^.*$', views.index, name='index')
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('my_blog/', include('my_blog.urls')),
    path('admin/', admin.site.urls),
]

my_site/my_blog/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):

    post_title = models.CharField(max_length=50)
    post_content = models.CharField(max_length=1000)
    published_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post_title

    def get_absolute_url(self):
        return reverse('my_blog:detail', kwargs={'pk': self.pk})

my_site/my_blog/views.py
from django.views import generic
from .models import Post
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import render
from django.contrib.auth import views


def index(request):
    return render(request, 'my_blog/index.html')


class ListView(generic.ListView):

    template_name = 'my_blog/list.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return Post.objects.all()


class DetailView(generic.DetailView):

    model = Post
    template_name = 'my_blog/detail.html'


class CreateView(generic.CreateView):

    model = Post
    template_name = 'my_blog/create.html'
    fields = ['post_title', 'post_content']


class EditView(generic.UpdateView):

    model = Post
    template_name = 'my_blog/edit.html'
    fields = ['post_title', 'post_content']

    def form_valid(self, form):
        form.instance.modified_date = timezone.now()
        return super().form_valid(form)


class DeleteView(generic.DeleteView):

    model = Post
    template_name = 'my_blog/delete.html'
    success_url = reverse_lazy('my_blog:list')


class LoginView(views.LoginView):

    template_name = 'my_blog/login.html'


class LogoutView(views.LogoutView):
    
    template_name = 'my_blog/logout.html'

my_site/my_blog/templates/base_templates/base_content_page.html
{% extends 'base_templates/base_page.html' %}
{% load static %}

{% block main %}
<div class="wrapper row1">
    <header id="header" class="hoc clear">
        <!-- Title -->
        {% block title %}
        {% endblock %}
        <!-- ################################################################################################ -->
    </header>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper bgded overlay light"
     style="background-image:url('{% static 'my_blog/images/home_main_p1-v1.jpg' %}');">
    <div id="breadcrumb" class="hoc clear">
        <!-- ################################################################################################ -->
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">Lorem</a></li>
            <li><a href="#">Ipsum</a></li>
            <li><a href="#">Dolor</a></li>
        </ul>
        <!-- ################################################################################################ -->
    </div>
</div>
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
    <main class="hoc container clear">
        <!-- main body -->
        <!-- ################################################################################################ -->
        {% block sidebar %}
        {% endblock %}
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        {% block content %}
        {% endblock %}
        <!-- ################################################################################################ -->
        <!-- / main body -->
        <div class="clear"></div>
    </main>
</div>
{% endblock %}

my_site/my_blog/templates/base_templates/base_page.html
<!DOCTYPE html>
<!--
Template Name: Jovaphile
Author: <a href="http://www.os-templates.com/">OS Templates</a>
Author URI: http://www.os-templates.com/
Licence: Free to use under our free template licence terms
Licence URI: http://www.os-templates.com/template-terms
-->
<html lang="">
<!-- To declare your language - read more here: https://www.w3.org/International/questions/qa-html-language-declarations -->
{% load static %}
<head>
    <title>Qile's Site</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link href="{% static 'my_blog/layout/styles/layout.css' %}" rel="stylesheet" type="text/css" media="all">
</head>
<body id="top">

<!-- Menu -->
<div class="wrapper row0">
    <nav id="mainav" class="hoc clear">
        <ul class="clear">

            <li><a href="{% url 'my_blog:index' %}">Home</a></li>
            <li><a href="{% url 'my_blog:list' %}">Blog</a></li>
            <li><a href="#">About Me</a></li>
        </ul>
    </nav>
</div>

<!-- Content -->
{% block main %}
{% endblock %}

<!-- PageFoot -->
<div class="wrapper row5">
    <div id="copyright" class="hoc clear">
        <p class="fl_left">Copyright &copy; 2017 - All Rights Reserved - <a href="#">Domain Name</a></p>
        <p class="fl_right">Template by <a target="_blank" href="http://www.os-templates.com/"
                                           title="Free Website Templates">OS Templates</a></p>
    </div>
</div>

<!-- GoTop -->
<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>

<!-- JAVASCRIPTS -->
<script src="{% static 'my_blog/layout/scripts/jquery.min.js' %}"></script>
<script src="{% static 'my_blog/layout/scripts/jquery.backtotop.js' %}"></script>
<script src="{% static 'my_blog/layout/scripts/jquery.mobilemenu.js' %}"></script>
</body>
</html>

my_site/my_blog/templates/my_blog/create.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>New Post</h1>
{% endblock %}

{% block content %}
<h1>New Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="create" value="Submit"/>
</form>
<a href="{% url 'my_blog:list' %}">Cancel</a>
{% endblock %}

my_site/my_blog/templates/my_blog/delete.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>Delete Post</h1>
{% endblock %}

{% block content %}
<h1>Delete Post</h1>
<p>Sure to delete post: {{ post.post_title }}</p>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="delete" value="delete"/>
</form>
<a href="{% url 'my_blog:detail' post.id%}">Cancel</a>
{% endblock %}

my_site/my_blog/templates/my_blog/detail.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>Post</h1>
{% endblock %}

{% block content %}
<h1>{{ post.post_title }}</h1>
<p> {{ post.post_content }} </p>
<div>Created on: {{ post.published_date }}</div> <div>Modified on: {{ post.modified_date }}</div>
<a href="{% url 'my_blog:delete' post.id %}">Delete</a>
<a href="{% url 'my_blog:edit' post.id %}">Edit</a>
<a href="{% url 'my_blog:list' %}">Back</a>
{% endblock %}

my_site/my_blog/templates/my_blog/edit.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>Edit Post</h1>
{% endblock %}

{% block content %}
<h1>{{ post.post_title }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="edit" value="edit" />
</form>
<a href="{% url 'my_blog:detail' post.id %}">Cancel</a>
{% endblock %}

my_site/my_blog/templates/my_blog/index.html
{% extends 'base_templates/base_page.html' %}

{% load static %}
{% block main %}
<div class="wrapper bgded overlay light" style="background-image:url('{% static 'my_blog/images/home_main_p1-v1.jpg' %}');">
  <div id="pageintro" class="hoc clear">
    <!-- ################################################################################################ -->
    <article>
      <h3 class="heading">Hello !</h3>
      <p>Welcome to Qile's site!</p>
      <footer>
        <ul class="nospace inline pushright">
          <li><a class="btn inverse" href="#">Enter ></a></li>
        </ul>
      </footer>
    </article>
    <!-- ################################################################################################ -->
  </div>
</div>
{% endblock %}

my_site/my_blog/templates/my_blog/list.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>My Posts</h1>
{% endblock %}

{% block content %}
<a href="{% url 'my_blog:create' %}">Create a new post</a>
<ul>
    {% for post in post_list %}
    <li>
        <h2>{{ post.post_title }}</h2>
        <p>{{ post.post_content|truncatechars:255 }}</p>
        <div>Created on: {{ post.published_date }}</div> <div>Modified on: {{ post.modified_date }}</div>
        <a href="{% url 'my_blog:detail' post.id %}">Detail</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

my_site/my_blog/templates/my_blog/login.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>Login</h1>
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="create" value="Submit"/>
</form>
<a href="{% url 'my_blog:list' %}">Cancel</a>
{% endblock %}

my_site/my_blog/templates/my_blog/logout.html
{% extends 'base_templates/base_content_page.html' %}

{% block title %}
<h1>Logged out</h1>
{% endblock %}

{% block content %}
<h2>You have logged out.</h2>
<a href="{% url 'my_blog:index' %}">Home page</a>
</br>
<a href="{% url 'my_blog:login' %}">Log in</a>
{% endblock %}